[Fix]初始化ec2要安裝docker以及docker-compose

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,6 +16,7 @@ jobs:
       CLIENT_PORT: ${{ vars.CLIENT_PORT }}
       DB_PORT: ${{ vars.DB_PORT }}
       DB_HOST: ${{ vars.DB_HOST }}
+      DB_NAME: ${{ vars.DB_NAME }}
       DB_USER: ${{ secrets.DB_USER }}
       DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
       MQTT_BROKER_URL: ${{ vars.MQTT_BROKER_URL }}
@@ -26,6 +27,7 @@ jobs:
       PASSPORT_SECRET: ${{ secrets.PASSPORT_SECRET }}
       JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
       REDIS_URL: ${{ vars.REDIS_URL }}
+      LOG_FILE: ${{ vars.LOG_FILE }}
 
     steps:
       - name: Connect to EC2
@@ -35,8 +37,17 @@ jobs:
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }} 
           script: |
-            sudo apt-get update && sudo apt-get install git -y || sudo yum install git -y
-
+            if ! command -v git &> /dev/null; then
+              echo "Git not found. Installing Git..."
+              if command -v apt-get &> /dev/null; then
+                sudo apt-get update && sudo apt-get install git -y
+              elif command -v yum &> /dev/null; then
+                sudo yum install git -y
+              fi
+            else
+              echo "Git is already installed."
+            fi
+            
             if [ ! -d "JobSubPub" ]; then 
               git clone -b test-deploying https://github.com/YiHsinTseng/JobSubPub.git
             fi
@@ -45,13 +56,14 @@ jobs:
             git fetch origin
             git reset --hard origin/test-deploying
 
-            cat <<EOF > .env
+            cat <<EOF > ./Docker/.env
             PORT=$PORT
             PUB_PORT=$PUB_PORT
             PUBLISH_CRON_TIME=$PUBLISH_CRON_TIME
             CLIENT_PORT=$CLIENT_PORT
             DB_PORT=$DB_PORT
             DB_HOST=$DB_HOST
+            DB_NAME=$DB_NAME
             DB_USER=$DB_USER
             DB_PASSWORD=$DB_PASSWORD
             MQTT_BROKER_URL=$MQTT_BROKER_URL
@@ -62,11 +74,32 @@ jobs:
             PASSPORT_SECRET=$PASSPORT_SECRET
             JWT_EXPIRES_IN=$JWT_EXPIRES_IN
             REDIS_URL=$REDIS_URL
+            LOG_FILE=$LOG_FILE
             EOF
 
             sudo chmod 600 .env
 
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing Docker..."
+              sudo yum update -y
+              sudo yum -y install docker
+              sudo service docker start
+              sudo systemctl enable docker
+            else
+              echo "Docker is already installed."
+            fi
+
+            DOCKER_COMPOSE_PATH="/usr/local/bin/docker-compose"
+
+            if [ ! -f "$DOCKER_COMPOSE_PATH" ]; then
+              echo "Docker Compose not found. Downloading..."
+              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o "$DOCKER_COMPOSE_PATH"
+              sudo chmod +x "$DOCKER_COMPOSE_PATH"
+            else
+              echo "Docker Compose is already installed."
+            fi
+
             cd Docker || exit
             sudo docker system prune -a -f
-            docker-compose down --rmi all
-            docker-compose up --build -d
+            sudo docker-compose down --rmi all
+            sudo docker-compose up --build -d
